# Generated by Django 2.2.13 on 2021-01-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendedor',
            new_name='seller',
        ),
    ]
